name: open_weather_flutter_app
description: A Flutter project designed and developed by Hussein Dbouk
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.7
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/loading_animation.gif
    - assets/cloudy_animation.gif
    - assets/rainy_animation.gif
    - assets/sunny_animation.gif
    - assets/rainy.jpg
    - assets/sunny_image.jpg
    - assets/cloudy_image.jpg
    - assets/error.jpg
    - assets/.env
